### ISSUE TITLE
Getting errors when preprocessing

### ISSUE THREAD

**Issue by danielinux7** [OpenNMT/nmt-wizard-docker#104]
Here is a screenshot, what am I doing wrong?
![Screenshot from 2019-09-02 11-13-06](https://user-images.githubusercontent.com/2645266/64099736-b0577c00-cd72-11e9-9411-9d71f6579549.png)
This is what I put in the config file:
![Screenshot from 2019-09-02 11-16-17](https://user-images.githubusercontent.com/2645266/64099926-278d1000-cd73-11e9-8b2f-3783585063a8.png)

**Comment by guillaumekln** [comment]
What are you trying to achieve with this project?

**Comment by danielinux7** [comment]
I want to build a simple website to serve machine translations for all languages, starting with endangered/under-represented languages, one of them is Russian-Abkhazian
I answered your question the way I understood it

**Comment by guillaumekln** [comment]
If you have a model trained with OpenNMT-tf, see https://github.com/OpenNMT/nmt-wizard-docker/issues/46#issuecomment-456795844 to start an inference server.

If you don't already have a model, I suggest ignoring this project for now and head over to https://github.com/OpenNMT/OpenNMT-tf to get started.

**Comment by danielinux7** [comment]
OK
