### ISSUE TITLE
Print the whole request on the server

### ISSUE THREAD

**Issue by panosk** [OpenNMT/nmt-wizard-docker#181]
Hello,

Is it possible to print the client's source text and the translation in the server while running the REST server?  I saw there is a DEBUG logging option in serving.py, will that do the trick and how can I enable it?

Thanks!

**Comment by guillaumekln** [comment]
Hi,

Yes, you can set the environment variable `LOG_LEVEL=DEBUG`.

**Comment by panosk** [comment]
Thanks!
