### ISSUE TITLE
Serving opennmt_tf framework

### ISSUE THREAD

**Issue by julsal** [OpenNMT/nmt-wizard-docker#46]
Dears, thanks for sharing this nice piece of work.

I'd like to serve the opennmt_tf framework using docker, exposing a web service as described in the main README (POST /translate).

As an example, I downloaded the trained corpus 'averaged-ende-export500k'. As far as I understood,  after building the Docker image, I need to run the image as :

`docker run -p 5000:5000 -v /root/models:/path/to/averaged-ende-export500k opennmt_tf:latest serve --host 0.0.0.0 --port 5000 --config config.json`

I have some questions about the configuration file.

```
{
    "source": "en",
    "target": "de",
    "model": "1539080952",  // (mandatory for trans, serve) Full model name as uuid64
    "imageTag": "string",  // (mandatory) Full URL of the image: url/image:tag.
    "tokenization": {
        // Vocabularies and tokenization options (from OpenNMT/Tokenizer).
        "source": {
            "vocabulary": "string"
            // other source specific tokenization options
        },
        "target": {
            "vocabulary": "string"
            // other target specific tokenization options
        }
    }
}
```

 I removed everything marked as optional. I guess uuid64 required in "model" is the directory name from the corpus averaged-ende-export500k.

Is everything correct up to this point?
What should I put in "imageTag" and "tokenization"?

**Comment by guillaumekln** [comment]
Hi,

Here are the steps to serve this pretrained model.

1. Download and adapt the model:

```bash
wget https://s3.amazonaws.com/opennmt-models/averaged-ende-export500k.tar.gz
tar xf averaged-ende-export500k.tar.gz
mv averaged-ende-export500k/1539080952/ averaged-ende-export500k/1
```

2. Create `config.json` in `averaged-ende-export500k`:

```json
{
    "source": "en",
    "target": "de",
    "model": "averaged-ende-export500k",
    "modelType": "release",
    "tokenization": {
        "source": {
            "mode": "none",
            "sp_model_path": "${MODEL_DIR}/1/assets.extra/wmtende.model",
            "vocabulary": "${MODEL_DIR}/1/assets/wmtende.vocab"
        },
        "target": {
            "mode": "none",
            "sp_model_path": "${MODEL_DIR}/1/assets.extra/wmtende.model",
            "vocabulary": "${MODEL_DIR}/1/assets/wmtende.vocab"
        }
    }
}
```

3. Run the server:

```bash
docker run -p 5000:5000 -v $PWD:/root/models nmtwizard/opennmt-tf --model averaged-ende-export500k --model_storage /root/models serve --host 0.0.0.0 --port 5000
```

4. Test the server:

```bash
$ curl -X POST http://localhost:5000/translate -d '{"src":[{"text": "Hello world!"}]}'
{"tgt": [[{"text": "Hallo Welt!", "score": -0.27484220266342163}, {"text": "Hallo!", "score": -1.6019006967544556}, {"text": "Hallo, die Welt!", "score": -0.8488588333129883}, {"text": "Hallo Welten!", "score": -1.1288902759552002}]]}
```

Hope this helps.

**Comment by julsal** [comment]
thank you very much, @guillaumekln Worked perfectly!

**Comment by yms9654** [comment]
@guillaumekln Can I add inference config in the `config.json`?
like this
```
"options": {
        "config": {
            "infer": {
                "n_best": 3,
                "with_scores": true,
                "with_alignments": "hard"
            },
            "score": {
                "with_alignments": "hard"
            }
        }
    }
```
I have tried but it is not working..
Do you have any idea on that?

Thank you!

**Comment by danielinux7** [comment]
Hello,
I'm getting these errors, what am I doing wrong?
![Screenshot from 2019-07-10 15-04-28](https://user-images.githubusercontent.com/2645266/60967820-3bdcff80-a324-11e9-8058-634669618a82.png)

**Comment by guillaumekln** [comment]
Did you follow step 1. in the instructions above? Make sure the directory `averaged-ende-export500k` exists in `$PWD`.

**Comment by danielinux7** [comment]
I followed step 1 inside root/models/ folder 
* I have to change: mv averaged-ende-export500k/**1539080952**/ averaged-ende-export500k/1
                        to: mv averaged-ende-export500k/**1554540232**/ averaged-ende-export500k/1
I followed everything as is, on step 3 I'm getting the same error.
I'm not sure what you mean by: 
> Make sure the directory averaged-ende-export500k exists in $PWD.

**Comment by guillaumekln** [comment]
When you run `ls $PWD`, does the directory `averaged-ende-export500k` exist?

**Comment by danielinux7** [comment]
@guillaumekln 
When I run it in the terminal inside root/models/, then yes it exists.
![Screenshot from 2019-07-11 14-08-45](https://user-images.githubusercontent.com/2645266/61046383-a73ad600-a3e5-11e9-85fe-e34991480336.png)

**Comment by guillaumekln** [comment]
Can you run the command from this directory?

**Comment by danielinux7** [comment]
@guillaumekln Can you be more clear, I can hardly understand you!

Yes, I run `ls $PWD` while I'm in `root/models/`
![Screenshot from 2019-07-11 16-34-10](https://user-images.githubusercontent.com/2645266/61055257-bc216480-a3f9-11e9-96c4-7c8b941f2376.png)

**Comment by guillaumekln** [comment]
You should run the Docker command when you are in `~/models`. Please note that the instructions above do not indicate to create a `models` directory or change directory.

**Comment by danielinux7** [comment]
@guillaumekln It's working!
I'm running the Docker command in ~/models. 
I did create root/models/ directory and execute the 1 step in there.
