### ISSUE TITLE
Preprocessing and training

### ISSUE THREAD

**Issue by julsal** [OpenNMT/nmt-wizard-docker#62]
I'm trying to train a model using this wizard. As `buildvocab` is not implemented, I generated the vocabulary using the `onmt-build-vocab`, and them run `preprocess` using the docker wizard, which outputs nothing. My config.json is as following:

```
{
    "source": "en",
    "target": "el",
    "model": "greek",
    "data": {
    },
    "tokenization": {
        "source": {
	    "vocabulary": "${CORPUS_DIR}/vocab/greek/en",
	    "mode": "aggressive"
        },
        "target": {
	    "vocabulary": "${CORPUS_DIR}/vocab/greek/el",
	    "mode": "aggressive"
        }
    },
    "options": {
    }
}
```

Do I really need to run `preprocess` before `train`? Does `process` generate the vocab, or am I right to provide it?  Do I need to state the vocabulary here in `config.json`, or it comes from CORPUS_DIR/vocab? What is BPE models? Should I include in vocab?

I tried to check the code from the error messages, but it seems to be different versions. Is the docker's latest image the correct to use?

Thanks a lot!

**Comment by guillaumekln** [comment]
> Do I really need to run preprocess before train?

No, the `train` command can preprocess the data given your tokenization configuration. You can also use `preprocess --build_model` to produce the preprocessing result and chain preprocess and training runs.

> Does process generate the vocab, or am I right to provide it?

Unfortunately there is no open source implementation of `buildvocab` right now so you are right to provide it. If you used `onmt-build-vocab`, you should also remove OpenNMT-tf [special tokens](http://opennmt.net/OpenNMT-tf/data.html#vocabulary) from this vocabulary.

> Do I need to state the vocabulary here in config.json, or it comes from CORPUS_DIR/vocab?

Your configuration is correct regarding the vocabulary.

> Is the docker's latest image the correct to use?

Yes.

---

Thanks for trying out this project! As it is mostly driven by internal uses, the documentation might be incomplete or unclear. It would benefit from an end-to-end tutorial.

**Comment by julsal** [comment]
Thanks for your answer. I'm still struggling to put it to run. 

What is the difference between CORPUS_DIR and MODELS_DIR? When I call `train`, it asks for a config file into` /root/models/<model name>/config.json`

I managed to run, but it says:

`INFO:tensorflow:Training on 1 examples`

and finishes quickly. My config file is as bellow:

```
{
    "source": "en",
    "target": "el",
    "model": "greek",
    "data": {
    },
    "tokenization": {
        "source": {
            "vocabulary": "${CORPUS_DIR}/vocab/greek/en",
            "mode": "aggressive"
        },
        "target": {
            "vocabulary": "${CORPUS_DIR}/vocab/greek/el",
            "mode": "aggressive"
        }
    },
    "options": {
        "model_type": "Transformer",
        "config": {
            "params": {
                "optimizer": "GradientDescentOptimizer",
                "learning_rate": 0.01,
                "param_init": 0.1,
                "clip_gradients": 5.0,
                "beam_width": 5
            },
            "train": {
                "batch_size": 64,
                "bucket_width": 2,
                "maximum_features_length": 50,
                "maximum_labels_length": 50,
                "save_checkpoints_steps": 5000,
                "keep_checkpoint_max": 8
            },
            "infer": {
                "batch_size": 32
            }
        }
    }
}
```

I'm using the europarl dataset to train a model from EN to EL.
Thanks, once again!
